name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.CD_DEPLOY_COMMAND != '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt

      - name: Run deploy command
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASIC_VALUE_IN_BYN: ${{ secrets.BASIC_VALUE_IN_BYN }}
          CONNECTION_TIMEOUT: ${{ secrets.CONNECTION_TIMEOUT }}
          CRM_DATABASE_URL: ${{ secrets.CRM_DATABASE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CRM_TIMEZONE: ${{ secrets.CRM_TIMEZONE }}
        run: ${{ secrets.CD_DEPLOY_COMMAND }}
